In [ ]:
import os
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/EM:IP/최종 데이터 파일/variables/0_start_with_2_original_cleaning.csv', sep=',')
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['time'] = df['time'].astype(float)
df

,Unnamed: 0,ID,cnt,schoolid,StIDStd,event,time,event_number,event_value,network,fare_type,ticket_type,number_trips,OECD,credit,timestamp,instance,instance_id
0,1,ARE000018904852,ARE,189,4852,START_ITEM,1186.7,1,Start,NaN,NaN,NaN,NaN,0,0,2021-12-22 14:19:00,1,ARE000018904852-01
1,2,ARE000018904852,ARE,189,4852,ACER_EVENT,1195.6,2,country_trains,country_trains,NaN,NaN,0.0,0,0,2021-12-22 14:19:00,3,ARE000018904852-03
2,3,ARE000018904852,ARE,189,4852,ACER_EVENT,1202.8,3,full_fare,country_trains,full_fare,NaN,0.0,0,0,2021-12-22 14:20:00,4,ARE000018904852-04
3,4,ARE000018904852,ARE,189,4852,ACER_EVENT,1217.2,4,daily,country_trains,full_fare,daily,0.0,0,0,2021-12-22 14:20:00,7,ARE000018904852-07
4,5,ARE000018904852,ARE,189,4852,ACER_EVENT,1223.7,5,Buy,country_trains,full_fare,daily,0.0,0,0,2021-12-22 14:20:00,10,ARE000018904852-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322839,322870,USA000007902365,USA,79,2365,ACER_EVENT,111.5,16,city_subway,city_subway,NaN,NaN,0.0,1,0,2021-12-22 14:01:00,2,USA000007902365-02
322840,322871,USA000007902365,USA,79,2365,ACER_EVENT,112.0,17,concession,city_subway,concession,NaN,0.0,1,0,2021-12-22 14:01:00,5,USA000007902365-05
322841,322872,USA000007902365,USA,79,2365,ACER_EVENT,113.1,18,daily,city_subway,concession,daily,0.0,1,0,2021-12-22 14:01:00,7,USA000007902365-07
322842,322873,USA000007902365,USA,79,2365,ACER_EVENT,128.6,19,Buy,city_subway,concession,daily,0.0,1,0,2021-12-22 14:02:00,10,USA000007902365-10
322843,322874,USA000007902365,USA,79,2365,END_ITEM,130.3,20,End,NaN,NaN,NaN,NaN,1,0,2021-12-22 14:02:00,12,USA000007902365-12

In [ ]:
##연속중복 행 제거

In [ ]:
df['reps'] = 0

for i in tqdm(range(len(df)-1)):
        if (df['ID'][i] == df['ID'][i+1]) and (df['instance'][i] == df['instance'][i+1]):
            df['reps'][i+1] = 1

100%|██████████| 322843/322843 [00:10<00:00, 31141.06it/s]

In [ ]:
# 연속으로 반복되는 행동이 아닌 경우 (reps=0)인 경우만 남김
df = df[(df['reps'] != 1)]
df = df.reset_index(drop = True)
df

,Unnamed: 0,ID,cnt,schoolid,StIDStd,event,time,event_number,event_value,network,fare_type,ticket_type,number_trips,OECD,credit,timestamp,instance,instance_id,reps
0,1,ARE000018904852,ARE,189,4852,START_ITEM,1186.7,1,Start,NaN,NaN,NaN,NaN,0,0,2021-12-22 14:19:00,1,ARE000018904852-01,0
1,2,ARE000018904852,ARE,189,4852,ACER_EVENT,1195.6,2,country_trains,country_trains,NaN,NaN,0.0,0,0,2021-12-22 14:19:00,3,ARE000018904852-03,0
2,3,ARE000018904852,ARE,189,4852,ACER_EVENT,1202.8,3,full_fare,country_trains,full_fare,NaN,0.0,0,0,2021-12-22 14:20:00,4,ARE000018904852-04,0
3,4,ARE000018904852,ARE,189,4852,ACER_EVENT,1217.2,4,daily,country_trains,full_fare,daily,0.0,0,0,2021-12-22 14:20:00,7,ARE000018904852-07,0
4,5,ARE000018904852,ARE,189,4852,ACER_EVENT,1223.7,5,Buy,country_trains,full_fare,daily,0.0,0,0,2021-12-22 14:20:00,10,ARE000018904852-10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313247,322870,USA000007902365,USA,79,2365,ACER_EVENT,111.5,16,city_subway,city_subway,NaN,NaN,0.0,1,0,2021-12-22 14:01:00,2,USA000007902365-02,0
313248,322871,USA000007902365,USA,79,2365,ACER_EVENT,112.0,17,concession,city_subway,concession,NaN,0.0,1,0,2021-12-22 14:01:00,5,USA000007902365-05,0
313249,322872,USA000007902365,USA,79,2365,ACER_EVENT,113.1,18,daily,city_subway,concession,daily,0.0,1,0,2021-12-22 14:01:00,7,USA000007902365-07,0
313250,322873,USA000007902365,USA,79,2365,ACER_EVENT,128.6,19,Buy,city_subway,concession,daily,0.0,1,0,2021-12-22 14:02:00,10,USA000007902365-10,0
313251,322874,USA000007902365,USA,79,2365,END_ITEM,130.3,20,End,NaN,NaN,NaN,NaN,1,0,2021-12-22 14:02:00,12,USA000007902365-12,0

In [ ]:
df.to_csv('0_StartWith_3_cleaning_final.csv', index=False)