In [ ]:
import os
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/EM:IP/정리/최종 데이터 파일/variables/0_StartWith_4_final.csv', sep=',')
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['time'] = df['time'].astype(float)
df

,number,ID,cnt,schoolid,StIDStd,event,time,event_number,event_value,network,fare_type,ticket_type,number_trips,OECD,credit,timestamp,instance,instance_id,reps
0,1,ARE000018904852,ARE,189,4852,START_ITEM,1186.7,1,Start,NaN,NaN,NaN,NaN,0,0,2021-12-22 14:19:00,1,ARE000018904852-01,0
1,2,ARE000018904852,ARE,189,4852,ACER_EVENT,1195.6,2,country_trains,country_trains,NaN,NaN,0.0,0,0,2021-12-22 14:19:00,3,ARE000018904852-03,0
2,3,ARE000018904852,ARE,189,4852,ACER_EVENT,1202.8,3,full_fare,country_trains,full_fare,NaN,0.0,0,0,2021-12-22 14:20:00,4,ARE000018904852-04,0
3,4,ARE000018904852,ARE,189,4852,ACER_EVENT,1217.2,4,daily,country_trains,full_fare,daily,0.0,0,0,2021-12-22 14:20:00,7,ARE000018904852-07,0
4,5,ARE000018904852,ARE,189,4852,ACER_EVENT,1223.7,5,Buy,country_trains,full_fare,daily,0.0,0,0,2021-12-22 14:20:00,10,ARE000018904852-10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313247,16,USA000007902365,USA,79,2365,ACER_EVENT,111.5,16,city_subway,city_subway,NaN,NaN,0.0,1,0,2021-12-22 14:01:00,2,USA000007902365-02,0
313248,17,USA000007902365,USA,79,2365,ACER_EVENT,112.0,17,concession,city_subway,concession,NaN,0.0,1,0,2021-12-22 14:01:00,5,USA000007902365-05,0
313249,18,USA000007902365,USA,79,2365,ACER_EVENT,113.1,18,daily,city_subway,concession,daily,0.0,1,0,2021-12-22 14:01:00,7,USA000007902365-07,0
313250,19,USA000007902365,USA,79,2365,ACER_EVENT,128.6,19,Buy,city_subway,concession,daily,0.0,1,0,2021-12-22 14:02:00,10,USA000007902365-10,0
313251,20,USA000007902365,USA,79,2365,END_ITEM,130.3,20,End,NaN,NaN,NaN,NaN,1,0,2021-12-22 14:02:00,12,USA000007902365-12,0

In [ ]:
df_action = df[['ID','event_value', 'event_number','instance','credit']]

In [ ]:
df_action['sequence']= ''
df_action["sequence"] = np.nan
df_action

,ID,event_value,event_number,instance,credit,sequence
0,ARE000018904852,Start,1,1,0,NaN
1,ARE000018904852,country_trains,2,3,0,NaN
2,ARE000018904852,full_fare,3,4,0,NaN
3,ARE000018904852,daily,4,7,0,NaN
4,ARE000018904852,Buy,5,10,0,NaN
...,...,...,...,...,...,...
313247,USA000007902365,city_subway,16,2,0,NaN
313248,USA000007902365,concession,17,5,0,NaN
313249,USA000007902365,daily,18,7,0,NaN
313250,USA000007902365,Buy,19,10,0,NaN
313251,USA000007902365,End,20,12,0,NaN

### a: city→concession→daily→cancel (2, 5, 7, 11)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==7) and (df_action['instance'][i+3]==11):
        df_action['sequence'][i:i+4]= 'a'

### b: city-concession-individual-trip4-buy (2, 5, 6, 9, 10)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==10):
        df_action['sequence'][i:i+5] = 'b'

### b: city-concession-individual-trip4-tripn-trip4-buy (2, 5, 6, 9, 8, 9, 10)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==8) and (df_action['instance'][i+5]==9) and (df_action['instance'][i+6]==10):
        df_action['sequence'][i:i+7] = 'b'

### b: city-concession-individual-trip4-tripn-trip4-tripn-trip4-buy (2, 5, 6, 9, 8, 9, 8, 9, 10)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==8) and (df_action['instance'][i+5]==9) and (df_action['instance'][i+6]==8) and (df_action['instance'][i+7]==9) and (df_action['instance'][i+8]==10):
        df_action['sequence'][i:i+9] = 'b'

### b: city-concession-individual-trip4-tripn-trip4-tripn-trip4-tripn-trip4-buy (2, 5, 6, 9, 8, 9, 8, 9, 8, 9, 10)

In [ ]:
 for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==8) and (df_action['instance'][i+5]==9) and (df_action['instance'][i+6]==8) and (df_action['instance'][i+7]==9) and (df_action['instance'][i+8]==8) and (df_action['instance'][i+9]==9) and (df_action['instance'][i+10]==10):
        df_action['sequence'][i:i+11] = 'b'

### b: city-concession-individual-trip4-tripn-trip4-tripn-trip4-tripn-trip4-tripn-trip4-buy (2, 5, 6, 9, 8, 9, 8, 9, 8, 9, 8, 9, 10)

In [ ]:
 for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==8) and (df_action['instance'][i+5]==9) and (df_action['instance'][i+6]==8) and (df_action['instance'][i+7]==9) and (df_action['instance'][i+8]==8) and (df_action['instance'][i+9]==9) and (df_action['instance'][i+10]==8) and (df_action['instance'][i+11]==9) and (df_action['instance'][i+12]==10):
        df_action['sequence'][i:i+13] = 'b'

### b: city-concession-individual-trip4-cancel (2, 5, 6, 9, 11)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==11):
        df_action['sequence'][i:i+5] = 'b'

### b: city-concession-individual-trip4-tripn-cancel (2, 5, 6, 9, 8, 11)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==8) and (df_action['instance'][i+5]==11):
        df_action['sequence'][i:i+6] = 'b'

### b: city-concession-individual-trip4-tripn-trip4-cancel (2, 5, 6, 9, 8, 9, 11)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==8) and (df_action['instance'][i+5]==9) and (df_action['instance'][i+6]==11):
        df_action['sequence'][i:i+7] = 'b'

### b: city-concession-individual-trip4-tripn-trip4-tripn-cancel (2, 5, 6, 9, 8, 9, 8, 11)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==8) and (df_action['instance'][i+5]==9) and (df_action['instance'][i+6]==8) and (df_action['instance'][i+7]==11):
        df_action['sequence'][i:i+8] = 'b'

### b: city-concession-individual-trip4-tripn-trip4-tripn-trip4-cancel (2, 5, 6, 9, 8, 9, 8, 9, 11)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==8) and (df_action['instance'][i+5]==9) and (df_action['instance'][i+6]==8) and (df_action['instance'][i+7]==9) and (df_action['instance'][i+8]==11):
        df_action['sequence'][i:i+9] = 'b'

### b: city-concession-individual-trip4-tripn-trip4-tripn-trip4-tripn-cancel (2, 5, 6, 9, 8, 9, 8, 9, 8, 11)

In [ ]:
 for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==8) and (df_action['instance'][i+5]==9) and (df_action['instance'][i+6]==8) and (df_action['instance'][i+7]==9) and (df_action['instance'][i+8]==8)  and (df_action['instance'][i+9]==11):
        df_action['sequence'][i:i+10] = 'b'

### b: city-concession-individual-trip4-tripn-trip4-tripn-trip4-tripn-trip4-cancel (2, 5, 6, 9, 8, 9, 8, 9, 8, 9, 11)

In [ ]:
 for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==8) and (df_action['instance'][i+5]==9) and (df_action['instance'][i+6]==8) and (df_action['instance'][i+7]==9) and (df_action['instance'][i+8]==8) and (df_action['instance'][i+9]==9) and (df_action['instance'][i+10]==11):
        df_action['sequence'][i:i+11] = 'b'

### b: city-concession-individual-trip4-tripn-trip4-tripn-trip4-tripn-trip4-tripn-cancel (2, 5, 6, 9, 8, 9, 8, 9, 8, 9, 8, 11)

In [ ]:
 for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==8) and (df_action['instance'][i+5]==9) and (df_action['instance'][i+6]==8) and (df_action['instance'][i+7]==9) and (df_action['instance'][i+8]==8) and (df_action['instance'][i+9]==9) and (df_action['instance'][i+10]==8) and (df_action['instance'][i+11]==11):
        df_action['sequence'][i:i+12] = 'b'

### b: city-concession-individual-trip4-tripn-trip4-tripn-trip4-tripn-trip4-tripn-trip4-cancel (2, 5, 6, 9, 8, 9, 8, 9, 8, 9, 8, 9, 11)

In [ ]:
 for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==9) and (df_action['instance'][i+4]==8) and (df_action['instance'][i+5]==9) and (df_action['instance'][i+6]==8) and (df_action['instance'][i+7]==9) and (df_action['instance'][i+8]==8) and (df_action['instance'][i+9]==9) and (df_action['instance'][i+10]==8) and (df_action['instance'][i+11]==9) and (df_action['instance'][i+12]==11):
        df_action['sequence'][i:i+13] = 'b'

### b: city-concession-individual-tripn-trip4-buy (2, 5, 6, 8, 9, 10)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==8) and (df_action['instance'][i+4]==9) and (df_action['instance'][i+5]==10):
        df_action['sequence'][i:i+6] = 'b'

### b: city-concession-individual-tripn-trip4-tripn-trip4-buy (2, 5, 6, 8, 9, 8, 9, 10)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==8) and (df_action['instance'][i+4]==9) and (df_action['instance'][i+5]==8) and (df_action['instance'][i+6]==9) and (df_action['instance'][i+7]==10):
        df_action['sequence'][i:i+8] = 'b'

### b: city-concession-individual-tripn-trip4-tripn-trip4-tripn-trip4-buy (2, 5, 6, 8, 9, 8, 9, 8, 9, 10)

In [ ]:
 for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==8) and (df_action['instance'][i+4]==9) and (df_action['instance'][i+5]==8) and (df_action['instance'][i+6]==9) and (df_action['instance'][i+7]==8) and (df_action['instance'][i+8]==9)  and (df_action['instance'][i+9]==10):
        df_action['sequence'][i:i+10] = 'b'

### b: city-concession-individual-tripn-trip4-tripn-trip4-tripn-trip4-tripn-trip4-buy (2, 5, 6, 8, 9, 8, 9, 8, 9, 8, 9, 10)

In [ ]:
 for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==8) and (df_action['instance'][i+4]==9) and (df_action['instance'][i+5]==8) and (df_action['instance'][i+6]==9) and (df_action['instance'][i+7]==8) and (df_action['instance'][i+8]==9) and (df_action['instance'][i+9]==8) and (df_action['instance'][i+10]==9) and (df_action['instance'][i+11]==10):
        df_action['sequence'][i:i+12] = 'b'

### b: city-concession-individual-tripn-trip4-cancel (2, 5, 6, 8, 9, 11)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==8) and (df_action['instance'][i+4]==9) and (df_action['instance'][i+5]==11):
        df_action['sequence'][i:i+6] = 'b'

### b: city-concession-individual-tripn-trip4-tripn-cancel (2, 5, 6, 8, 9, 8, 11)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==8) and (df_action['instance'][i+4]==9) and (df_action['instance'][i+5]==8) and (df_action['instance'][i+6]==11):
        df_action['sequence'][i:i+7] = 'b'

### b: city-concession-individual-tripn-trip4-tripn-trip4-cancel (2, 5, 6, 8, 9, 8, 9, 11)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==8) and (df_action['instance'][i+4]==9) and (df_action['instance'][i+5]==8) and (df_action['instance'][i+6]==9) and (df_action['instance'][i+7]==11):
        df_action['sequence'][i:i+8] = 'b'

### b: city-concession-individual-tripn-trip4-tripn-trip4-tripn-cancel (2, 5, 6, 8, 9, 8, 9, 8, 11)

In [ ]:
for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==8) and (df_action['instance'][i+4]==9) and (df_action['instance'][i+5]==8) and (df_action['instance'][i+6]==9) and (df_action['instance'][i+7]==8) and (df_action['instance'][i+8]==11):
        df_action['sequence'][i:i+9] = 'b'

### b: city-concession-individual-tripn-trip4-tripn-trip4-tripn-trip4-cancel (2, 5, 6, 8, 9, 8, 9, 8, 9, 11)

In [ ]:
 for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==8) and (df_action['instance'][i+4]==9) and (df_action['instance'][i+5]==8) and (df_action['instance'][i+6]==9) and (df_action['instance'][i+7]==8) and (df_action['instance'][i+8]==9)  and (df_action['instance'][i+9]==11):
        df_action['sequence'][i:i+10] = 'b'

### b: city-concession-individual-tripn-trip4-tripn-trip4-tripn-trip4-tripn-cancel (2, 5, 6, 8, 9, 8, 9, 8, 9, 8, 11)

In [ ]:
 for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==8) and (df_action['instance'][i+4]==9) and (df_action['instance'][i+5]==8) and (df_action['instance'][i+6]==9) and (df_action['instance'][i+7]==8) and (df_action['instance'][i+8]==9) and (df_action['instance'][i+9]==8) and (df_action['instance'][i+10]==11):
        df_action['sequence'][i:i+11] = 'b'

### b: city-concession-individual-tripn-trip4-tripn-trip4-tripn-trip4-tripn-trip4-cancel (2, 5, 6, 8, 9, 8, 9, 8, 9, 8, 9, 11)

In [ ]:
 for i in range(len(df_action)):
    if(df_action['instance'][i]==2) and (df_action['instance'][i+1]==5) and (df_action['instance'][i+2]==6) and (df_action['instance'][i+3]==8) and (df_action['instance'][i+4]==9) and (df_action['instance'][i+5]==8) and (df_action['instance'][i+6]==9) and (df_action['instance'][i+7]==8) and (df_action['instance'][i+8]==9) and (df_action['instance'][i+9]==8) and (df_action['instance'][i+10]==9) and (df_action['instance'][i+11]==11):
        df_action['sequence'][i:i+12] = 'b'

In [ ]:
df_action.tail(50)

,ID,event_value,event_number,instance,credit,sequence
313202,USA000007902371,Buy,13,10,1,b
313203,USA000007902371,End,14,12,1,NaN
313204,USA000007902381,Start,1,1,1,NaN
313205,USA000007902381,city_subway,2,2,1,b
313206,USA000007902381,concession,3,5,1,b
313207,USA000007902381,individual,4,6,1,b
313208,USA000007902381,trip_n,5,8,1,b
313209,USA000007902381,trip_4,13,9,1,b
313210,USA000007902381,trip_n,14,8,1,b
313211,USA000007902381,trip_4,15,9,1,b
313212,USA000007902381,trip_n,16,8,1,b
313213,USA000007902381,trip_4,20,9,1,b
313214,USA000007902381,trip_n,21,8,1,b
313215,USA000007902381,trip_4,22,9,1,b
313216,USA000007902381,Cancel,23,11,1,b
313217,USA000007902381,country_trains,24,3,1,NaN
313218,USA000007902381,concession,25,5,1,NaN
313219,USA000007902381,individual,26,6,1,NaN
313220,USA000007902381,trip_4,27,9,1,NaN
313221,USA000007902381,Cancel,28,11,1,NaN
313222,USA000007902381,city_subway,29,2,1,a
313223,USA000007902381,concession,30,5,1,a
313224,USA000007902381,daily,31,7,1,a
313225,USA000007902381,Cancel,32,11,1,a
313226,USA000007902381,city_subway,33,2,1,b
313227,USA000007902381,concession,34,5,1,b
313228,USA000007902381,individual,35,6,1,b
313229,USA000007902381,trip_4,36,9,1,b
313230,USA000007902381,Buy,37,10,1,b
313231,USA000007902381,End,38,12,1,NaN
313232,USA000007902365,Start,1,1,0,NaN
313233,USA000007902365,city_subway,2,2,0,a
313234,USA000007902365,concession,3,5,0,a
313235,USA000007902365,daily,4,7,0,a
313236,USA000007902365,Cancel,5,11,0,a
313237,USA000007902365,country_trains,6,3,0,NaN
313238,USA000007902365,full_fare,7,4,0,NaN
313239,USA000007902365,Cancel,8,11,0,NaN
313240,USA000007902365,country_trains,9,3,0,NaN
313241,USA000007902365,concession,10,5,0,NaN
313242,USA000007902365,daily,11,7,0,NaN
313243,USA000007902365,Cancel,12,11,0,NaN
313244,USA000007902365,city_subway,13,2,0,NaN
313245,USA000007902365,full_fare,14,4,0,NaN
313246,USA000007902365,Cancel,15,11,0,NaN
313247,USA000007902365,city_subway,16,2,0,NaN
313248,USA000007902365,concession,17,5,0,NaN
313249,USA000007902365,daily,18,7,0,NaN
313250,USA000007902365,Buy,19,10,0,NaN
313251,USA000007902365,End,20,12,0,NaN

In [ ]:
# 정답 이외의 행동은 모두 c로 처리
df_action = df_action.fillna('c')

### Start, End 삭제

In [ ]:
idx = df_action[df_action['event_value']=='Start'].index
df_action = df_action.drop(idx)

In [ ]:
idx = df_action[df_action['event_value']=='End'].index
df_action = df_action.drop(idx)

In [ ]:
df_action.tail(60)

,ID,event_value,event_number,instance,credit,sequence
313185,USA000007902358,concession,7,5,1,b
313186,USA000007902358,individual,8,6,1,b
313187,USA000007902358,trip_4,9,9,1,b
313188,USA000007902358,Buy,10,10,1,b
313191,USA000007902371,city_subway,2,2,1,a
313192,USA000007902371,concession,3,5,1,a
313193,USA000007902371,daily,4,7,1,a
313194,USA000007902371,Cancel,5,11,1,a
313195,USA000007902371,city_subway,6,2,1,b
313196,USA000007902371,concession,7,5,1,b
313197,USA000007902371,individual,8,6,1,b
313198,USA000007902371,trip_n,9,8,1,b
313199,USA000007902371,trip_4,10,9,1,b
313200,USA000007902371,trip_n,11,8,1,b
313201,USA000007902371,trip_4,12,9,1,b
313202,USA000007902371,Buy,13,10,1,b
313205,USA000007902381,city_subway,2,2,1,b
313206,USA000007902381,concession,3,5,1,b
313207,USA000007902381,individual,4,6,1,b
313208,USA000007902381,trip_n,5,8,1,b
313209,USA000007902381,trip_4,13,9,1,b
313210,USA000007902381,trip_n,14,8,1,b
313211,USA000007902381,trip_4,15,9,1,b
313212,USA000007902381,trip_n,16,8,1,b
313213,USA000007902381,trip_4,20,9,1,b
313214,USA000007902381,trip_n,21,8,1,b
313215,USA000007902381,trip_4,22,9,1,b
313216,USA000007902381,Cancel,23,11,1,b
313217,USA000007902381,country_trains,24,3,1,c
313218,USA000007902381,concession,25,5,1,c
313219,USA000007902381,individual,26,6,1,c
313220,USA000007902381,trip_4,27,9,1,c
313221,USA000007902381,Cancel,28,11,1,c
313222,USA000007902381,city_subway,29,2,1,a
313223,USA000007902381,concession,30,5,1,a
313224,USA000007902381,daily,31,7,1,a
313225,USA000007902381,Cancel,32,11,1,a
313226,USA000007902381,city_subway,33,2,1,b
313227,USA000007902381,concession,34,5,1,b
313228,USA000007902381,individual,35,6,1,b
313229,USA000007902381,trip_4,36,9,1,b
313230,USA000007902381,Buy,37,10,1,b
313233,USA000007902365,city_subway,2,2,0,a
313234,USA000007902365,concession,3,5,0,a
313235,USA000007902365,daily,4,7,0,a
313236,USA000007902365,Cancel,5,11,0,a
313237,USA000007902365,country_trains,6,3,0,c
313238,USA000007902365,full_fare,7,4,0,c
313239,USA000007902365,Cancel,8,11,0,c
313240,USA000007902365,country_trains,9,3,0,c
313241,USA000007902365,concession,10,5,0,c
313242,USA000007902365,daily,11,7,0,c
313243,USA000007902365,Cancel,12,11,0,c
313244,USA000007902365,city_subway,13,2,0,c
313245,USA000007902365,full_fare,14,4,0,c
313246,USA000007902365,Cancel,15,11,0,c
313247,USA000007902365,city_subway,16,2,0,c
313248,USA000007902365,concession,17,5,0,c
313249,USA000007902365,daily,18,7,0,c
313250,USA000007902365,Buy,19,10,0,c

In [ ]:
df_action['final_sequence'] = ''
df_action["final_sequence"] = np.nan
df_action

,ID,event_value,event_number,instance,credit,sequence,final_sequence
1,ARE000018904852,country_trains,2,3,0,c,NaN
2,ARE000018904852,full_fare,3,4,0,c,NaN
3,ARE000018904852,daily,4,7,0,c,NaN
4,ARE000018904852,Buy,5,10,0,c,NaN
7,ARE000018904861,country_trains,2,3,0,c,NaN
...,...,...,...,...,...,...,...
313246,USA000007902365,Cancel,15,11,0,c,NaN
313247,USA000007902365,city_subway,16,2,0,c,NaN
313248,USA000007902365,concession,17,5,0,c,NaN
313249,USA000007902365,daily,18,7,0,c,NaN
313250,USA000007902365,Buy,19,10,0,c,NaN

In [ ]:
df_action.to_csv('1_GenerateVariables_2_sequence_abs.csv', index=False)

### 시퀀스 열 만들기(a, b는 연속으로 중복될 경우 하나만 쓰고, c는 모두 남김; ex. aaabbbbcc인경우 abcc로 만듦)

In [ ]:
df_action = pd.read_csv('/content/1_GenerateVariables_2_sequence_abs.csv')

In [ ]:
df_action.tail(50)

,ID,event_value,event_number,instance,credit,sequence,final_sequence
252260,USA000007902371,individual,8,6,1,b,NaN
252261,USA000007902371,trip_n,9,8,1,b,NaN
252262,USA000007902371,trip_4,10,9,1,b,NaN
252263,USA000007902371,trip_n,11,8,1,b,NaN
252264,USA000007902371,trip_4,12,9,1,b,NaN
252265,USA000007902371,Buy,13,10,1,b,NaN
252266,USA000007902381,city_subway,2,2,1,b,NaN
252267,USA000007902381,concession,3,5,1,b,NaN
252268,USA000007902381,individual,4,6,1,b,NaN
252269,USA000007902381,trip_n,5,8,1,b,NaN
252270,USA000007902381,trip_4,13,9,1,b,NaN
252271,USA000007902381,trip_n,14,8,1,b,NaN
252272,USA000007902381,trip_4,15,9,1,b,NaN
252273,USA000007902381,trip_n,16,8,1,b,NaN
252274,USA000007902381,trip_4,20,9,1,b,NaN
252275,USA000007902381,trip_n,21,8,1,b,NaN
252276,USA000007902381,trip_4,22,9,1,b,NaN
252277,USA000007902381,Cancel,23,11,1,b,NaN
252278,USA000007902381,country_trains,24,3,1,c,NaN
252279,USA000007902381,concession,25,5,1,c,NaN
252280,USA000007902381,individual,26,6,1,c,NaN
252281,USA000007902381,trip_4,27,9,1,c,NaN
252282,USA000007902381,Cancel,28,11,1,c,NaN
252283,USA000007902381,city_subway,29,2,1,a,NaN
252284,USA000007902381,concession,30,5,1,a,NaN
252285,USA000007902381,daily,31,7,1,a,NaN
252286,USA000007902381,Cancel,32,11,1,a,NaN
252287,USA000007902381,city_subway,33,2,1,b,NaN
252288,USA000007902381,concession,34,5,1,b,NaN
252289,USA000007902381,individual,35,6,1,b,NaN
252290,USA000007902381,trip_4,36,9,1,b,NaN
252291,USA000007902381,Buy,37,10,1,b,NaN
252292,USA000007902365,city_subway,2,2,0,a,NaN
252293,USA000007902365,concession,3,5,0,a,NaN
252294,USA000007902365,daily,4,7,0,a,NaN
252295,USA000007902365,Cancel,5,11,0,a,NaN
252296,USA000007902365,country_trains,6,3,0,c,NaN
252297,USA000007902365,full_fare,7,4,0,c,NaN
252298,USA000007902365,Cancel,8,11,0,c,NaN
252299,USA000007902365,country_trains,9,3,0,c,NaN
252300,USA000007902365,concession,10,5,0,c,NaN
252301,USA000007902365,daily,11,7,0,c,NaN
252302,USA000007902365,Cancel,12,11,0,c,NaN
252303,USA000007902365,city_subway,13,2,0,c,NaN
252304,USA000007902365,full_fare,14,4,0,c,NaN
252305,USA000007902365,Cancel,15,11,0,c,NaN
252306,USA000007902365,city_subway,16,2,0,c,NaN
252307,USA000007902365,concession,17,5,0,c,NaN
252308,USA000007902365,daily,18,7,0,c,NaN
252309,USA000007902365,Buy,19,10,0,c,NaN

In [ ]:
# b 13개짜리 (Buy)-> 마지막 1개만 final_sequence에 남기기
for i in range(len(df_action)-12):
    if (df_action['event_value'][i+12]=='Buy') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['ID'][i+6]==df_action['ID'][i+7]) and (df_action['ID'][i+7]==df_action['ID'][i+8]) and (df_action['ID'][i+8]==df_action['ID'][i+9]) and (df_action['ID'][i+9]==df_action['ID'][i+10]) and (df_action['ID'][i+10]==df_action['ID'][i+11]) and (df_action['ID'][i+11]==df_action['ID'][i+12]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b') and (df_action['sequence'][i+7]=='b') and (df_action['sequence'][i+8]=='b') and (df_action['sequence'][i+9]=='b') and (df_action['sequence'][i+10]=='b') and (df_action['sequence'][i+11]=='b') and (df_action['sequence'][i+12]=='b'):
        df_action['final_sequence'][i+12]='b'

In [ ]:
# b 13개짜리 (Cancel)
for i in range(len(df_action)-12):
    if (df_action['event_value'][i+12]=='Cancel') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['ID'][i+6]==df_action['ID'][i+7]) and (df_action['ID'][i+7]==df_action['ID'][i+8]) and (df_action['ID'][i+8]==df_action['ID'][i+9]) and (df_action['ID'][i+9]==df_action['ID'][i+10]) and (df_action['ID'][i+10]==df_action['ID'][i+11]) and (df_action['ID'][i+11]==df_action['ID'][i+12]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b') and (df_action['sequence'][i+7]=='b') and (df_action['sequence'][i+8]=='b') and (df_action['sequence'][i+9]=='b') and (df_action['sequence'][i+10]=='b') and (df_action['sequence'][i+11]=='b') and (df_action['sequence'][i+12]=='b'):
        df_action['final_sequence'][i+12]='b'

In [ ]:
# b 12개짜리 (Buy)
for i in range(len(df_action)-11):
    if (df_action['event_value'][i+11]=='Buy') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['ID'][i+6]==df_action['ID'][i+7]) and (df_action['ID'][i+7]==df_action['ID'][i+8]) and (df_action['ID'][i+8]==df_action['ID'][i+9]) and (df_action['ID'][i+9]==df_action['ID'][i+10]) and (df_action['ID'][i+10]==df_action['ID'][i+11]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b') and (df_action['sequence'][i+7]=='b') and (df_action['sequence'][i+8]=='b') and (df_action['sequence'][i+9]=='b') and (df_action['sequence'][i+10]=='b') and (df_action['sequence'][i+11]=='b'):
        df_action['final_sequence'][i+11]='b'

In [ ]:
# b 12개짜리(Cancel)
for i in range(len(df_action)-11):
    if (df_action['event_value'][i+11]=='Cancel') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['ID'][i+6]==df_action['ID'][i+7]) and (df_action['ID'][i+7]==df_action['ID'][i+8]) and (df_action['ID'][i+8]==df_action['ID'][i+9]) and (df_action['ID'][i+9]==df_action['ID'][i+10]) and (df_action['ID'][i+10]==df_action['ID'][i+11]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b') and (df_action['sequence'][i+7]=='b') and (df_action['sequence'][i+8]=='b') and (df_action['sequence'][i+9]=='b') and (df_action['sequence'][i+10]=='b') and (df_action['sequence'][i+11]=='b'):
        df_action['final_sequence'][i+11]='b'

In [ ]:
# b 11개짜리(Buy)
for i in range(len(df_action)-10):
    if (df_action['event_value'][i]=='city_subway') and (df_action['event_value'][i+10]=='Buy') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['ID'][i+6]==df_action['ID'][i+7]) and (df_action['ID'][i+7]==df_action['ID'][i+8]) and (df_action['ID'][i+8]==df_action['ID'][i+9]) and (df_action['ID'][i+9]==df_action['ID'][i+10]) and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b') and (df_action['sequence'][i+7]=='b') and (df_action['sequence'][i+8]=='b') and (df_action['sequence'][i+9]=='b') and (df_action['sequence'][i+10]=='b'):
        df_action['final_sequence'][i+10]='b'

In [ ]:
# b 11개짜리(Cancel)
for i in range(len(df_action)-10):
    if (df_action['event_value'][i]=='city_subway') and (df_action['event_value'][i+10]=='Cancel') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['ID'][i+6]==df_action['ID'][i+7]) and (df_action['ID'][i+7]==df_action['ID'][i+8]) and (df_action['ID'][i+8]==df_action['ID'][i+9]) and (df_action['ID'][i+9]==df_action['ID'][i+10]) and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b') and (df_action['sequence'][i+7]=='b') and (df_action['sequence'][i+8]=='b') and (df_action['sequence'][i+9]=='b') and (df_action['sequence'][i+10]=='b'):
        df_action['final_sequence'][i+10]='b'

In [ ]:
# b 10개짜리(Buy)
for i in range(len(df_action)-9):
    if (df_action['event_value'][i+9]=='Buy') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['ID'][i+6]==df_action['ID'][i+7]) and (df_action['ID'][i+7]==df_action['ID'][i+8]) and (df_action['ID'][i+8]==df_action['ID'][i+9]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b') and (df_action['sequence'][i+7]=='b') and (df_action['sequence'][i+8]=='b') and (df_action['sequence'][i+9]=='b'):
        df_action['final_sequence'][i+9]='b'

In [ ]:
# b 10개짜리(Cancel)
for i in range(len(df_action)-9):
    if (df_action['event_value'][i+9]=='Cancel') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['ID'][i+6]==df_action['ID'][i+7]) and (df_action['ID'][i+7]==df_action['ID'][i+8]) and (df_action['ID'][i+8]==df_action['ID'][i+9]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b') and (df_action['sequence'][i+7]=='b') and (df_action['sequence'][i+8]=='b') and (df_action['sequence'][i+9]=='b'):
        df_action['final_sequence'][i+9]='b'

In [ ]:
# b 9개짜리(Buy)
for i in range(len(df_action)-8):
    if (df_action['event_value'][i+8]=='Buy') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['ID'][i+6]==df_action['ID'][i+7]) and (df_action['ID'][i+7]==df_action['ID'][i+8]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b') and (df_action['sequence'][i+7]=='b') and (df_action['sequence'][i+8]=='b'):
        df_action['final_sequence'][i+8]='b'

In [ ]:
# b 9개짜리(Cancel)
for i in range(len(df_action)-8):
    if (df_action['event_value'][i+8]=='Cancel') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['ID'][i+6]==df_action['ID'][i+7]) and (df_action['ID'][i+7]==df_action['ID'][i+8]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b') and (df_action['sequence'][i+7]=='b') and (df_action['sequence'][i+8]=='b'):
        df_action['final_sequence'][i+8]='b'

In [ ]:
# b 8개짜리(Buy)
for i in range(len(df_action)-7):
    if (df_action['event_value'][i+7]=='Buy') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['ID'][i+6]==df_action['ID'][i+7]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b') and (df_action['sequence'][i+7]=='b'):
        df_action['final_sequence'][i+7]='b'

In [ ]:
# b 8개짜리(Cancel)
for i in range(len(df_action)-7):
    if (df_action['event_value'][i+7]=='Cancel') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['ID'][i+6]==df_action['ID'][i+7]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b') and (df_action['sequence'][i+7]=='b'):
        df_action['final_sequence'][i+7]='b'

In [ ]:
# b 7개짜리(Buy)
for i in range(len(df_action)-6):
    if (df_action['event_value'][i+6]=='Buy') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b'):
        df_action['final_sequence'][i+6]='b'

In [ ]:
# b 7개짜리(Cancel)
for i in range(len(df_action)-6):
    if (df_action['event_value'][i+6]=='Cancel') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['ID'][i+5]==df_action['ID'][i+6]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b') and (df_action['sequence'][i+6]=='b'):
        df_action['final_sequence'][i+6]='b'

In [ ]:
# b 6개짜리(Buy)
for i in range(len(df_action)-5):
    if (df_action['event_value'][i+5]=='Buy') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b'):
        df_action['final_sequence'][i+5]='b'

In [ ]:
# b 6개짜리(Cancel)
for i in range(len(df_action)-5):
    if (df_action['event_value'][i+5]=='Cancel') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['ID'][i+4]==df_action['ID'][i+5]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b') and (df_action['sequence'][i+5]=='b'):
        df_action['final_sequence'][i+5]='b'

In [ ]:
# b 5개짜리(Buy)
for i in range(len(df_action)-4):
    if (df_action['event_value'][i+4]=='Buy') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b'):
        df_action['final_sequence'][i+4]='b'

In [ ]:
# b 5개짜리(Cancel)
for i in range(len(df_action)-4):
    if (df_action['event_value'][i+4]=='Cancel') and (df_action['ID'][i]==df_action['ID'][i+1]) and (df_action['ID'][i+1]==df_action['ID'][i+2]) and (df_action['ID'][i+2]==df_action['ID'][i+3]) and (df_action['ID'][i+3]==df_action['ID'][i+4]) and (df_action['event_value'][i]=='city_subway') and (df_action['sequence'][i]=='b') and (df_action['sequence'][i+1]=='b') and (df_action['sequence'][i+2]=='b') and (df_action['sequence'][i+3]=='b') and (df_action['sequence'][i+4]=='b'):
        df_action['final_sequence'][i+4]='b'

In [ ]:
# a 4개짜리
for i in range(len(df_action)-3):
    if (df_action['sequence'][i]=='a') and (df_action['sequence'][i+1]=='a') and (df_action['sequence'][i+2]=='a') and (df_action['sequence'][i+3]=='a'):
        df_action['final_sequence'][i+3]='a'

In [ ]:
df_action.tail(60)

,ID,event_value,event_number,instance,credit,sequence,final_sequence
252250,USA000007902358,concession,7,5,1,b,NaN
252251,USA000007902358,individual,8,6,1,b,NaN
252252,USA000007902358,trip_4,9,9,1,b,NaN
252253,USA000007902358,Buy,10,10,1,b,b
252254,USA000007902371,city_subway,2,2,1,a,NaN
252255,USA000007902371,concession,3,5,1,a,NaN
252256,USA000007902371,daily,4,7,1,a,NaN
252257,USA000007902371,Cancel,5,11,1,a,a
252258,USA000007902371,city_subway,6,2,1,b,NaN
252259,USA000007902371,concession,7,5,1,b,NaN
252260,USA000007902371,individual,8,6,1,b,NaN
252261,USA000007902371,trip_n,9,8,1,b,NaN
252262,USA000007902371,trip_4,10,9,1,b,NaN
252263,USA000007902371,trip_n,11,8,1,b,NaN
252264,USA000007902371,trip_4,12,9,1,b,NaN
252265,USA000007902371,Buy,13,10,1,b,b
252266,USA000007902381,city_subway,2,2,1,b,NaN
252267,USA000007902381,concession,3,5,1,b,NaN
252268,USA000007902381,individual,4,6,1,b,NaN
252269,USA000007902381,trip_n,5,8,1,b,NaN
252270,USA000007902381,trip_4,13,9,1,b,NaN
252271,USA000007902381,trip_n,14,8,1,b,NaN
252272,USA000007902381,trip_4,15,9,1,b,NaN
252273,USA000007902381,trip_n,16,8,1,b,NaN
252274,USA000007902381,trip_4,20,9,1,b,NaN
252275,USA000007902381,trip_n,21,8,1,b,NaN
252276,USA000007902381,trip_4,22,9,1,b,NaN
252277,USA000007902381,Cancel,23,11,1,b,b
252278,USA000007902381,country_trains,24,3,1,c,NaN
252279,USA000007902381,concession,25,5,1,c,NaN
252280,USA000007902381,individual,26,6,1,c,NaN
252281,USA000007902381,trip_4,27,9,1,c,NaN
252282,USA000007902381,Cancel,28,11,1,c,NaN
252283,USA000007902381,city_subway,29,2,1,a,NaN
252284,USA000007902381,concession,30,5,1,a,NaN
252285,USA000007902381,daily,31,7,1,a,NaN
252286,USA000007902381,Cancel,32,11,1,a,a
252287,USA000007902381,city_subway,33,2,1,b,NaN
252288,USA000007902381,concession,34,5,1,b,NaN
252289,USA000007902381,individual,35,6,1,b,NaN
252290,USA000007902381,trip_4,36,9,1,b,NaN
252291,USA000007902381,Buy,37,10,1,b,b
252292,USA000007902365,city_subway,2,2,0,a,NaN
252293,USA000007902365,concession,3,5,0,a,NaN
252294,USA000007902365,daily,4,7,0,a,NaN
252295,USA000007902365,Cancel,5,11,0,a,a
252296,USA000007902365,country_trains,6,3,0,c,NaN
252297,USA000007902365,full_fare,7,4,0,c,NaN
252298,USA000007902365,Cancel,8,11,0,c,NaN
252299,USA000007902365,country_trains,9,3,0,c,NaN
252300,USA000007902365,concession,10,5,0,c,NaN
252301,USA000007902365,daily,11,7,0,c,NaN
252302,USA000007902365,Cancel,12,11,0,c,NaN
252303,USA000007902365,city_subway,13,2,0,c,NaN
252304,USA000007902365,full_fare,14,4,0,c,NaN
252305,USA000007902365,Cancel,15,11,0,c,NaN
252306,USA000007902365,city_subway,16,2,0,c,NaN
252307,USA000007902365,concession,17,5,0,c,NaN
252308,USA000007902365,daily,18,7,0,c,NaN
252309,USA000007902365,Buy,19,10,0,c,NaN

In [ ]:
# a, b결측제거(=마지막만 남김)
df_without_c = df_action.dropna(axis=0)

### c없는 문자열 만들기

In [ ]:
new_stu_id = df_without_c['ID'].unique().tolist()
len(new_stu_id)

15011

In [ ]:
# 문자열 합치기
full_sequence = []
for i in tqdm(new_stu_id):
    a = df_without_c[df_without_c['ID']==i]
    
    seq1 = a['sequence'].tolist()
    seq2 = ''.join(seq1)
    full_sequence.append(seq2)

100%|██████████| 15011/15011 [00:30<00:00, 489.82it/s]

In [ ]:
df_seq_no_c = pd.DataFrame({'stu_id':new_stu_id, 'sequence':full_sequence})
df_seq_no_c.tail(20)

                stu_id sequence
14991  USA000010603226       ab
14992  USA000010603244        b
14993  USA000013003978        b
14994  USA000013003967        b
14995  USA000008902703        a
14996  USA000015804888       ab
14997  USA000015804879      bab
14998  USA000015804866        b
14999  USA000015904912        b
15000  USA000015904901     abab
15001  USA000010403183       ab
15002  USA000013604188        b
15003  USA000013604175     abab
15004  USA000013604190        b
15005  USA000015004612       ab
15006  USA000015004637       ab
15007  USA000007902358       ab
15008  USA000007902371       ab
15009  USA000007902381      bab
15010  USA000007902365        a

In [ ]:
df_seq_no_c['length'] = ''
df_seq_no_c["length"] = np.nan

In [ ]:
for i in range(len(df_seq_no_c)):
    df_seq_no_c['length'][i] = len(df_seq_no_c['sequence'][i])

In [ ]:
df_seq_no_c.tail(20)

                stu_id sequence  length
14991  USA000010603226       ab     2.0
14992  USA000010603244        b     1.0
14993  USA000013003978        b     1.0
14994  USA000013003967        b     1.0
14995  USA000008902703        a     1.0
14996  USA000015804888       ab     2.0
14997  USA000015804879      bab     3.0
14998  USA000015804866        b     1.0
14999  USA000015904912        b     1.0
15000  USA000015904901     abab     4.0
15001  USA000010403183       ab     2.0
15002  USA000013604188        b     1.0
15003  USA000013604175     abab     4.0
15004  USA000013604190        b     1.0
15005  USA000015004612       ab     2.0
15006  USA000015004637       ab     2.0
15007  USA000007902358       ab     2.0
15008  USA000007902371       ab     2.0
15009  USA000007902381      bab     3.0
15010  USA000007902365        a     1.0

In [ ]:
df_seq_no_c.to_csv('1_GenerateVariables_2_sequence_abs_and_length.csv', index=False)

### 시퀀스 열 만들기 (a, b, c 포함)

In [ ]:
# for i in range(len(df_action)):
#    if (df_action['sequence'][i]=='c'):
#        df_action['final_sequence'][i]='c'

In [ ]:
# a, b결측제거(=마지막만 남김)
# df = df_action.dropna(axis=0)

In [ ]:
# new_stu_id = df['ID'].unique().tolist()
# len(new_stu_id)

In [ ]:
# 문자열 합치기
# full_sequence = []
# for i in tqdm(new_stu_id):
#    a = df[df['ID']==i]
#    
#    seq1 = a['sequence'].tolist()
#    seq2 = ''.join(seq1)
#    full_sequence.append(seq2)

In [ ]:
# 학생 당 점수 붙이기
# credit = []
# for i in tqdm(new_stu_id):
#    a = df[df['ID']==i]
#    stu_credit = min(a['credit'])
#    credit.append(stu_credit)

In [ ]:
# df_seq = pd.DataFrame({'stu_id':new_stu_id, 'credit':credit, 'sequence':full_sequence})
# df_seq.tail(20)

In [ ]:
# df_seq['length'] = ''
# df_seq["length"] = np.nan

In [ ]:
# for i in range(len(df_seq)):
#    df_seq['length'][i] = len(df_seq['sequence'][i])