In [ ]:
import os
import numpy as np
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df_o = pd.read_csv('/content/drive/MyDrive/EM:IP/정리/최종 데이터 파일/variables/2_ExploratoryAnalysis_0_start_with_full_credit.csv', index_col = False)

In [ ]:
df = df_o[['ID','cnt','time_A_total','time_b1','time_b2','time_B_total','time_start','time_end','time_solving','time_total', 'time_answer','time_not_answer','avg_time_btw_events','length','events_num','credit','OECD']]
df['length'] = df['length'].astype(int)
df['time_start'] = df['time_start'].astype(float)
df['time_end'] = df['time_end'].astype(float)
df['time_solving'] = df['time_solving'].astype(float)
df['time_total'] = df['time_total'].astype(float)
df['time_answer'] = df['time_answer'].astype(float)
df['time_not_answer'] = df['time_not_answer'].astype(float)
df['avg_time_btw_events'] = df['avg_time_btw_events'].astype(float)
df.set_index('ID', inplace=True)
df

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000027907117,ARE,10.5,8.0,35.4,43.4,154.4,2.8,64.3,221.5,53.9,10.4,4.286667,3,15,1,0
ARE000011302798,ARE,145.8,7.2,0.0,7.2,28.4,3.0,218.0,249.4,153.0,65.0,7.266667,3,30,1,0
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1

In [ ]:
# time_start IQR
timestart_25 = np.quantile(df['time_start'], 0.25)
timestart_75 = np.quantile(df['time_start'],0.75)
timestart_IQR = timestart_75 - timestart_25
timestart_min = timestart_25 - 7.0 * timestart_IQR
timestart_max = timestart_75 + 7.0 * timestart_IQR
df_1 = df[(timestart_min <= df['time_start']) & (df['time_start'] <= timestart_max)]
df_1

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000011302798,ARE,145.8,7.2,0.0,7.2,28.4,3.0,218.0,249.4,153.0,65.0,7.266667,3,30,1,0
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
ARE000024506213,ARE,4.7,4.3,22.5,26.8,7.6,5.7,38.6,51.9,31.5,7.1,2.144444,4,18,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1

In [ ]:
# time_A_total IQR
timeA_25 = np.quantile(df['time_A_total'], 0.25)
timeA_75 = np.quantile(df['time_A_total'],0.75)
timeA_IQR = timeA_75 - timeA_25
timeA_min = timeA_25 - 7.0 * timeA_IQR
timeA_max = timeA_75 + 7.0 * timeA_IQR
df_2 = df[(timeA_min <= df['time_A_total']) & (df['time_A_total'] <= timeA_max)]
df_2

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000027907117,ARE,10.5,8.0,35.4,43.4,154.4,2.8,64.3,221.5,53.9,10.4,4.286667,3,15,1,0
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
ARE000024506213,ARE,4.7,4.3,22.5,26.8,7.6,5.7,38.6,51.9,31.5,7.1,2.144444,4,18,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1

In [ ]:
# time_b1 IQR
timeb1_25 = np.quantile(df['time_b1'], 0.25)
timeb1_75 = np.quantile(df['time_b1'],0.75)
timeb1_IQR = timeb1_75 - timeb1_25
timeb1_min = timeb1_25 - 7.0 * timeb1_IQR
timeb1_max = timeb1_75 + 7.0 * timeb1_IQR
df_3 = df[(timeb1_min <= df['time_b1']) & (df['time_b1'] <= timeb1_max)]
df_3

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000027907117,ARE,10.5,8.0,35.4,43.4,154.4,2.8,64.3,221.5,53.9,10.4,4.286667,3,15,1,0
ARE000011302798,ARE,145.8,7.2,0.0,7.2,28.4,3.0,218.0,249.4,153.0,65.0,7.266667,3,30,1,0
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1

In [ ]:
# time_b2 IQR
timeb2_25 = np.quantile(df['time_b2'], 0.25)
timeb2_75 = np.quantile(df['time_b2'],0.75)
timeb2_IQR = timeb2_75 - timeb2_25
timeb2_min = timeb2_25 - 7.0 * timeb2_IQR
timeb2_max = timeb2_75 + 7.0 * timeb2_IQR
df_4 = df[(timeb2_min <= df['time_b2']) & (df['time_b2'] <= timeb2_max)]
df_4

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000027907117,ARE,10.5,8.0,35.4,43.4,154.4,2.8,64.3,221.5,53.9,10.4,4.286667,3,15,1,0
ARE000011302798,ARE,145.8,7.2,0.0,7.2,28.4,3.0,218.0,249.4,153.0,65.0,7.266667,3,30,1,0
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1

In [ ]:
# time_solving IQR
timeS_25 = np.quantile(df['time_solving'], 0.25)
timeS_75 = np.quantile(df['time_solving'],0.75)
timeS_IQR = timeS_75 - timeS_25
timeS_min = timeS_25 - 7.0 * timeS_IQR
timeS_max = timeS_75 + 7.0 * timeS_IQR
df_5 = df[(timeS_min <= df['time_solving']) & (df['time_solving'] <= timeS_max)]
df_5

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000027907117,ARE,10.5,8.0,35.4,43.4,154.4,2.8,64.3,221.5,53.9,10.4,4.286667,3,15,1,0
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
ARE000024506213,ARE,4.7,4.3,22.5,26.8,7.6,5.7,38.6,51.9,31.5,7.1,2.144444,4,18,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1

In [ ]:
# time_total IQR
timeT_25 = np.quantile(df['time_total'], 0.25)
timeT_75 = np.quantile(df['time_total'],0.75)
timeT_IQR = timeT_75 - timeT_25
timeT_min = timeT_25 - 7.0 * timeT_IQR
timeT_max = timeT_75 + 7.0 * timeT_IQR
df_6 = df[(timeT_min <= df['time_total']) & (df['time_total'] <= timeT_max)]
df_6

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000027907117,ARE,10.5,8.0,35.4,43.4,154.4,2.8,64.3,221.5,53.9,10.4,4.286667,3,15,1,0
ARE000011302798,ARE,145.8,7.2,0.0,7.2,28.4,3.0,218.0,249.4,153.0,65.0,7.266667,3,30,1,0
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1

In [ ]:
# time_answer IQR
answer_25 = np.quantile(df['time_answer'], 0.25)
answer_75 = np.quantile(df['time_answer'],0.75)
answer_IQR = answer_75 - answer_25
answer_min = answer_25 - 7.0 * answer_IQR
answer_max = answer_75 + 7.0 * answer_IQR
df_7 = df[(answer_min <= df['time_answer']) & (df['time_answer'] <= answer_max)]
df_7

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000027907117,ARE,10.5,8.0,35.4,43.4,154.4,2.8,64.3,221.5,53.9,10.4,4.286667,3,15,1,0
ARE000011302798,ARE,145.8,7.2,0.0,7.2,28.4,3.0,218.0,249.4,153.0,65.0,7.266667,3,30,1,0
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1

In [ ]:
# time_not_answer IQR
notanswer_25 = np.quantile(df['time_not_answer'], 0.25)
notanswer_75 = np.quantile(df['time_not_answer'],0.75)
notanswer_IQR = notanswer_75 - notanswer_25
notanswer_min = notanswer_25 - 7.0 * notanswer_IQR
notanswer_max = notanswer_75 + 7.0 * notanswer_IQR
df_8 = df[(notanswer_min <= df['time_not_answer']) & (df['time_not_answer'] <= notanswer_max)]
df_8

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000027907117,ARE,10.5,8.0,35.4,43.4,154.4,2.8,64.3,221.5,53.9,10.4,4.286667,3,15,1,0
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
ARE000024506213,ARE,4.7,4.3,22.5,26.8,7.6,5.7,38.6,51.9,31.5,7.1,2.144444,4,18,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1

In [ ]:
df['avg_time_btw_events']

ID
ARE000027907117    4.286667
ARE000011302798    7.266667
ARE000018804820    5.880000
ARE000039910042    1.634884
ARE000006001557    3.524000
                     ...
USA000015004612    2.250000
USA000015004637    4.170000
USA000007902358    6.275000
USA000007902371    4.545455
USA000007902381    3.188000
Name: avg_time_btw_events, Length: 7195, dtype: float64

In [ ]:
# avg_time_btw_events IQR
btw_25 = np.quantile(df['avg_time_btw_events'], 0.25)
btw_75 = np.quantile(df['avg_time_btw_events'],0.75)
btw_IQR = btw_75 - btw_25
btw_min = btw_25 - 7.0 * btw_IQR
btw_max = btw_75 + 7.0 * btw_IQR
df_9 = df[(btw_min <= df['avg_time_btw_events']) & (df['avg_time_btw_events'] <= btw_max)]
df_9

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000027907117,ARE,10.5,8.0,35.4,43.4,154.4,2.8,64.3,221.5,53.9,10.4,4.286667,3,15,1,0
ARE000011302798,ARE,145.8,7.2,0.0,7.2,28.4,3.0,218.0,249.4,153.0,65.0,7.266667,3,30,1,0
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1

In [ ]:
np.quantile(df['avg_time_btw_events'], 0.5)

3.0

In [ ]:
# length IQR
length_25 = np.quantile(df['length'], 0.25)
length_75 = np.quantile(df['length'],0.75)
length_IQR = length_75 - length_25
length_min = length_25 - 7.0 * length_IQR
length_max = length_75 + 7.0 * length_IQR
df_10 = df[(length_min <= df['length']) & (df['length'] <= length_max)]
df_10

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000027907117,ARE,10.5,8.0,35.4,43.4,154.4,2.8,64.3,221.5,53.9,10.4,4.286667,3,15,1,0
ARE000011302798,ARE,145.8,7.2,0.0,7.2,28.4,3.0,218.0,249.4,153.0,65.0,7.266667,3,30,1,0
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1

In [ ]:
len(df)

7195

In [ ]:
# 7.0기준 클리닝(103개 제거,  7195-7092)
df_fc_7 = df[((timestart_min <= df['time_start']) & (df['time_start'] <= timestart_max) &
              (timeA_min <= df['time_A_total']) & (df['time_A_total'] <= timeA_max) &
              (timeb1_min <= df['time_b1']) & (df['time_b1'] <= timeb1_max) & (timeb2_min <= df['time_b2']) & (df['time_b2'] <= timeb2_max) &
              (timeS_min <= df['time_solving']) & (df['time_solving'] <= timeS_max) &
              (timeT_min <= df['time_total']) & (df['time_total'] <= timeT_max) &
              (answer_min <= df['time_answer']) & (df['time_answer'] <= answer_max) &
              (notanswer_min <= df['time_not_answer']) & (df['time_not_answer'] <= notanswer_max) &
              (btw_min <= df['avg_time_btw_events']) & (df['avg_time_btw_events'] <= btw_max) &
              (length_min <= df['length']) & (df['length'] <= length_max))]
df_fc_7

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
ARE000024506213,ARE,4.7,4.3,22.5,26.8,7.6,5.7,38.6,51.9,31.5,7.1,2.144444,4,18,1,0
ARE000006601699,ARE,27.6,11.8,0.0,11.8,19.2,2.2,52.9,74.3,39.4,13.5,4.069231,2,13,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1

In [ ]:
df_fc_7.to_csv('3_OutliersNormalization_3_FullC_7.0.csv')

In [ ]:
#4.5기준 클리닝 (406개 제거)
df_5 = df[((timestart_min <= df['time_start']) & (df['time_start'] <= timestart_max) & (length_min <= df['length']) & (df['length'] <= length_max) & (btw_min <= df['avg_time_btw_events']) & (df['avg_time_btw_events'] <= btw_max) & (notanswer_min <= df['time_not_answer']) & (df['time_not_answer'] <= notanswer_max))]
df_5

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
ARE000024506213,ARE,4.7,4.3,22.5,26.8,7.6,5.7,38.6,51.9,31.5,7.1,2.144444,4,18,1,0
ARE000006601699,ARE,27.6,11.8,0.0,11.8,19.2,2.2,52.9,74.3,39.4,13.5,4.069231,2,13,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1

In [ ]:
#4.0기준 클리닝 (544개 제거)
df_6 = df[((timestart_min <= df['time_start']) & (df['time_start'] <= timestart_max) & (length_min <= df['length']) & (df['length'] <= length_max) & (btw_min <= df['avg_time_btw_events']) & (df['avg_time_btw_events'] <= btw_max) & (notanswer_min <= df['time_not_answer']) & (df['time_not_answer'] <= notanswer_max))]
df_6

,cnt,time_A_total,time_b1,time_b2,time_B_total,time_start,time_end,time_solving,time_total,time_answer,time_not_answer,avg_time_btw_events,length,events_num,credit,OECD
ID,,,,,,,,,,,,,,,,
ARE000018804820,ARE,45.4,10.5,0.0,10.5,40.8,8.6,58.8,108.2,55.9,2.9,5.880000,2,10,1,0
ARE000039910042,ARE,10.9,4.3,26.2,30.5,20.8,3.2,70.3,94.3,41.4,28.9,1.634884,5,43,1,0
ARE000006001557,ARE,23.9,3.8,30.5,34.3,9.3,3.3,88.1,100.7,58.2,29.9,3.524000,4,25,1,0
ARE000024506213,ARE,4.7,4.3,22.5,26.8,7.6,5.7,38.6,51.9,31.5,7.1,2.144444,4,18,1,0
ARE000006601699,ARE,27.6,11.8,0.0,11.8,19.2,2.2,52.9,74.3,39.4,13.5,4.069231,2,13,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
USA000015004612,USA,8.1,8.3,0.0,8.3,15.7,4.6,18.0,38.3,16.4,1.6,2.250000,2,8,1,1
USA000015004637,USA,25.8,11.5,0.0,11.5,19.8,2.5,41.7,64.0,37.3,4.4,4.170000,2,10,1,1
USA000007902358,USA,35.9,12.9,0.0,12.9,24.7,6.4,50.2,81.3,48.8,1.4,6.275000,2,8,1,1
USA000007902371,USA,33.3,15.8,0.0,15.8,11.9,12.5,50.0,74.4,49.1,0.9,4.545455,2,11,1,1
USA000007902381,USA,9.1,5.9,49.4,55.3,11.3,4.4,79.7,95.4,64.4,15.3,3.188000,3,25,1,1